/**
 * Shared image cache types — used by every project that consumes the cache.
 *
 * Cache keys follow the pattern: `<project>/<category>/<key>` (or with an
 * optional `/<subkey>` for showcase-style entries with multiple images).
 *
 * Examples:
 *   tdf/destinations/scottsdale-az
 *   tdf/bachelorParty/scottsdale-az
 *   tdf/guides/golf-trip-budget-guide
 *   bestman/showcases/derek-nashville-tn/bars
 *   bestman/showcases/derek-nashville-tn/lodging
 *   bestman/cities/austin-tx
 *   moh/cities/nashville-tn
 *   peptide/heroes/semaglutide
 *
 * Different projects use different key shapes — the cache doesn't enforce.
 * Projects that need to look up an image just import the JSON and read by key.
 */

export interface CacheEntry {
  /** Direct CDN URL to the optimized image. */
  url: string;
  /** Alt text — from Unsplash API or the search query. */
  alt: string;
  /** Photographer's display name (Unsplash TOS requirement). */
  photographerName: string;
  /** Link to photographer profile, with utm tracking. */
  photographerUrl: string;
  /** Link to the photo page on Unsplash, with utm tracking. */
  unsplashUrl: string;
  /** The query string that produced this result. */
  query: string;
  /** ISO timestamp of when the entry was fetched. */
  fetchedAt: string;
  /**
   * Source project that requested this entry — useful for re-fetch decisions
   * (e.g., re-query if the source project's content has shifted).
   */
  addedBy: string;
  /**
   * Human verification that the PHOTO shows what the key claims — OO#52's
   * setting-tile contract generalized upstream. The stamp binds to the photo
   * id (`photoIdFromUrl(entry.url)` at verification time, e.g.
   * `unsplash:1446038202205-1c9643...`), NEVER to the key: if a re-fetch
   * swaps the photo, `verified.photoId` no longer matches the URL and every
   * consumer must treat the entry as UNVERIFIED (render its fallback rather
   * than unreviewed pixels). The gate (scripts/check-duplicate-fanout.ts)
   * fails a stale stamp so it cannot linger. A stamp is only ever written by
   * a human who VIEWED the rendered pixels at the production crop — never
   * from a filename, an alt text, or a 200 OK
   * (feedback_verify_image_subject_matches_label).
   */
  verified?: {
    /** photoIdFromUrl(url) at the moment of verification. */
    photoId: string;
    /** What the viewed photo actually shows, stated as evidence. */
    subject: string;
    /** ISO date of the viewing. */
    verifiedAt: string;
  };
}

/**
 * The shared cache is a flat dict — every entry is keyed by its full path.
 * This makes lookups O(1) and serialization trivial.
 */
export type Cache = Record<string, CacheEntry>;

/**
 * A query item to feed the fetcher — describes what to look up and where
 * to store the result.
 */
export interface QueryItem {
  /** Full cache key, e.g. `tdf/destinations/scottsdale-az`. */
  key: string;
  /** Primary search query. */
  query: string;
  /**
   * Optional fallback query if the primary returns no results.
   *
   * NEVER set on a `<project>/venues/<slug>` key: a named venue's photo is an
   * identity claim, and a generic second query answers a different question
   * ("show me *a* castle") than the key asks ("show me Ashford Castle").
   * lib/query-policy.ts fails the build on one, and scripts/fetch.ts strips
   * any that survives a stale snapshot.
   */
  fallbackQuery?: string;
  /** Source project tag (stored on the entry). */
  addedBy: string;
  /** Human-readable label for log lines. */
  label?: string;
  /**
   * This query string was written and reviewed BY A HUMAN at the production
   * crop, not generated by a template. Exempts the item from the templated-
   * query hygiene rules (no lighting words, no staged emotion, ≤6 terms, no
   * widening fallback) and from nothing else — engagedmoon queries "dusk" on
   * purpose. Never set it on a string a loop produced.
   */
  curated?: boolean;
}

// ── M6 fields (CORPUS-M6 spec §2a/§2b, 2026-09-25) ─────────────────────────
//
// Additive: the 8 fields above are kept verbatim. `unsplashUrl` stays as a
// deprecated alias (it holds a pexels.com page on Pexels rows — the misname
// that credited Pexels photos "on Unsplash"); new consumers read `sourceUrl`
// and `credit` instead. Every writer produces these through ONE function,
// `toM6Entry` (lib/m6.ts), and `npm run gate:m6` fails a row that lacks them.

/** Only these two. Google Places, the runtime Unsplash pool and scraped venue
 * photos are fenced out on purpose (spec §1d) — none can enter by accident. */
export type Provider = "unsplash" | "pexels";
export type Licence = "unsplash-api" | "pexels-api";

export interface M6Credit {
  /**
   * true only if photographerName is non-empty AND photographerUrl is a
   * profile page (`unsplash.com/@user` | `www.pexels.com/@user`) AND
   * sourceUrl is an id-only photo page. Derived, never asserted by hand.
   */
  complete: boolean;
  /** "Photo by {name} on {Unsplash|Pexels}" when complete; "" when not — never a fallback string. */
  text: string;
  photographerName: string;
  /** Profile URL with NO query (utm is added by the consumer); "" if the row has no profile. */
  photographerUrl: string;
  /** "https://unsplash.com" | "https://www.pexels.com", no query. */
  providerUrl: string;
}

export interface M6Fields {
  /** From the CDN host; always equals the `photoIdFromUrl(url)` prefix. */
  provider: Provider;
  /** `photoIdFromUrl(url)`, e.g. "pexels:6944344". */
  photoId: string;
  licence: Licence;
  /**
   * ID-ONLY photo page, no slug, no query:
   *   pexels:   https://www.pexels.com/photo/<id>/   (<id> = the CDN id)
   *   unsplash: https://unsplash.com/photos/<shortId> (last 11 chars of the page path)
   * "" when no photo page is known.
   */
  sourceUrl: string;
  credit: M6Credit;
}

export type CacheEntryM6 = CacheEntry & M6Fields;

/** A human-viewed judgment (verdicts.json). Append-only; never written by the fetcher. */
export interface ImageVerdict {
  /** Full cache key, or "offsite-override/<name>" for OO's site-local overrides. */
  key: string;
  /** The photo that was VIEWED (`photoIdFromUrl` form). */
  photoId: string;
  verdict: "match" | "mismatch";
  /** What the viewed frame shows. */
  shows: string;
  /** The production crop it was viewed at. `surface` is from the closed list in lib/verdicts.ts. */
  crop: { surface: string; w: number; h: number; fit: "cover" | "contain" };
  /** Session / PR ref; never a script name. */
  verifiedBy: string;
  /** ISO date. */
  verifiedAt: string;
  evidence?: string;
  /** "<repo>@<sha>:<path>" for lifted rows. */
  liftedFrom?: string;
}

export type VerdictStatus = "denied" | "verified" | "stale" | "unverified";
