#!/bin/bash
# Keep the CI question-set current as shared-data grows.
# Wired via launchd (com.ncmills.image-snapshot-refresh), daily 07:20.
#
# ── WHY THIS EXISTS ─────────────────────────────────────────────────────────
# On CI the sibling project repos are not checked out, so every loader falls
# back to queries.snapshot.json. That file IS the autonomous fetcher's input:
# a destination absent from it is never photographed, and nothing reports it.
#
# check-snapshot-drift catches one half of that — a LOADER edited after the
# snapshot was committed. It cannot catch the other half, which is the common
# one: shared-data gains 40 destinations, a site bumps its pin, and the loader
# file never changes while its OUTPUT does. The snapshot silently under-asks
# and the new cities render the branded fallback forever.
#
# Only a machine with the sibling checkouts can regenerate it. That is this
# laptop, so this runs here.
#
# ── WHY IT IS SAFE TO RUN UNATTENDED ────────────────────────────────────────
# The dangerous outcome would be writing a SMALLER snapshot because a sibling
# repo was missing or mid-rebase — CI would then quietly stop asking for those
# images. buildSnapshot() already refuses to do that: an absent data dir marks
# the slice `preserved` and carries the previous queries AND their original
# timestamp through untouched. Worst case here is a no-op, never a shrink.
#
# The gate still runs before anything is committed, and a failure exits
# non-zero with the reason rather than pushing.
set -euo pipefail

REPO="$HOME/shared-image-cache"
LOG="$HOME/work/logs/image-snapshot-refresh.log"
mkdir -p "$HOME/work/logs"

say() { echo "$(date +%FT%T) $*" >> "$LOG"; }

cd "$REPO"

# Never regenerate on top of local work. A dirty tree means a human or another
# session is mid-change; committing over it would be theft, and `git pull
# --rebase` refuses outright. Checking the WHOLE tree, not just the snapshot:
# the first version of this guard watched only queries.snapshot.json and the
# pull then died on unrelated unstaged files — a scheduled job must never fight
# a working tree it does not own.
#
# SKIP, exit 0, not a failure: a laptop mid-edit is the normal state of this
# machine, and a nightly job that alarms on it is one whose log stops being read.
if [ -n "$(git status --porcelain)" ]; then
  say "SKIP — working tree is dirty (someone is mid-change); will try again tomorrow"
  exit 0
fi

git pull --quiet --rebase origin main || { say "FAIL — git pull"; exit 1; }

npx tsx scripts/snapshot-queries.ts >> "$LOG" 2>&1 || { say "FAIL — snapshot generation"; exit 1; }

if [ -z "$(git status --porcelain -- queries.snapshot.json)" ]; then
  say "no change — snapshot already current"
  exit 0
fi

# What actually moved, so the log answers "why did this commit happen".
DELTA=$(node -e '
  const {execSync}=require("child_process");
  const cur=JSON.parse(require("fs").readFileSync("queries.snapshot.json","utf8"));
  const prev=JSON.parse(execSync("git show HEAD:queries.snapshot.json",{encoding:"utf8"}));
  const out=[];
  for (const p of Object.keys(cur.projects)) {
    const a=(prev.projects?.[p]||[]).length, b=cur.projects[p].length;
    if (a!==b) out.push(`${p} ${a}->${b}`);
  }
  process.stdout.write(out.join(", ") || "same counts, different queries");
')

npm run gate >> "$LOG" 2>&1 || { say "FAIL — gate rejected the new snapshot ($DELTA); NOT committing"; exit 1; }

git add queries.snapshot.json
git commit --quiet -m "snapshot: refresh CI query set ($DELTA)

Regenerated by com.ncmills.image-snapshot-refresh. The sibling repos' data
changed without their loaders changing — shared-data growth, a pin bump, or new
destinations — so the questions CI asks were behind the catalogue.

Co-Authored-By: Claude Opus 5 (1M context) <noreply@anthropic.com>" || { say "FAIL — commit"; exit 1; }

git push --quiet origin main || { say "FAIL — push (commit is local)"; exit 1; }

say "refreshed + pushed: $DELTA"
